export const mockApprovements = [
  {
    id: -1,
    shortName: "Срочно! Через 1 день пройдет 1 день",
    mainWords: "день, срочно",
    from: "aboba",
    to: "aboba2",
    received: "12-11-2025",
    approvers: "Нет данных",
    inputText:
      "Одной из ключевых задач при использовании полиномиальной регрессии...",
    outputText:
      "Одной из ключевых задач при использовании полиномиальной регрессии...",
  },
  {
    id: -2,
    shortName: "Запрос по документу",
    mainWords: "запрос, документ",
    from: "client@bank.com",
    to: "employee@bank.com",
    received: "19-11-2025",
    approvers: "Нет данных",
    inputText: "Просим предоставить обновлённую версию отчёта.",
    outputText: "Добрый день! Отчёт отправлю в течение дня.",
  },
  {
    id: -3,
    shortName: "Проблема с поставкой",
    mainWords: "поставка, задержка",
    from: "supply@corp.com",
    to: "logistics@corp.com",
    received: "15-11-2025",
    approvers: "Нет данных",
    inputText: "Возникла задержка отправки груза.",
    outputText: "Уточню у партнёров и дам обновление.",
  },
  {
    id: -4,
    shortName: "Запрос на согласование бюджета",
    mainWords: "бюджет, согласование",
    from: "manager@corp.com",
    to: "finance@corp.com",
    received: "14-11-2025",
    approvers: "Нет данных",
    inputText: "Прошу согласовать бюджет на следующий квартал.",
    outputText: "Бюджет принят.",
  },
  {
    id: -5,
    shortName: "Смена расписания встреч",
    mainWords: "встреча, расписание",
    from: "ceo@corp.com",
    to: "assistant@corp.com",
    received: "13-11-2025",
    approvers: "Нет данных",
    inputText: "Перенеси встречу с партнёрами на 17:00.",
    outputText: "Перенёс, участники уведомлены.",
  },
];
